### ISSUE TITLE
Meeting like minded people

### ISSUE THREAD

**Issue by AydinCodes** [Enebz/MineSweeper#2]
Hi, my name's Aydin. I'm a 22 year old from Melbourne, Australia. I saw your issue 'Basic ThreadedWebsocketManager example doesn't work. #1243', and I'm wondering if you managed to create a trading bot? I'm currently going through a course and watching a bunch of YouTube for mine. I'm always looking for people who have the same interests as me, and would love to make new friends. Feel free to add me on discord: AydinMate#9207

**Comment by Enebz** [comment]
I did not manage to create a bot using the newest version of the framework, but I did build one with 1.0.15. I never tested it with real money, only paper. The bot is configured so you can easily add different strategies, but I have become quite better at programming, so I would rather build a new one than use the one I have built.
